# Generated by Django 2.1.7 on 2019-03-04 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CropInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('product_quantity_si', models.CharField(max_length=10)),
                ('date_of_use', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CropManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=400)),
                ('activity_status', models.CharField(max_length=300)),
                ('comment', models.TextField()),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('profile_image', models.ImageField(null=True, upload_to='processors')),
                ('phone_number', models.IntegerField()),
                ('started_work', models.DateField()),
                ('gender', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('village_name', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now=True)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('farm_code', models.CharField(max_length=200)),
                ('farm_size_ha', models.IntegerField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.ExtensionWorker')),
            ],
        ),
        migrations.CreateModel(
            name='FarmAnimals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=50)),
                ('number_of_animals', models.IntegerField()),
                ('percentage_as_manure', models.IntegerField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_crop', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='FarmPractices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_irrigation', models.BooleanField(default=False)),
                ('sprinkler_irrigation', models.BooleanField(default=False)),
                ('drip_irrigation', models.BooleanField(default=False)),
                ('natural_enemies', models.BooleanField(default=False)),
                ('animal_manure', models.BooleanField(default=False)),
                ('green_manure', models.BooleanField(default=False)),
                ('compost_used_per_ha', models.BooleanField(default=False)),
                ('animal_manure_quantity', models.IntegerField()),
                ('compost_used_quantity', models.IntegerField()),
                ('manua_weeding', models.BooleanField(default=False)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Farm')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.ExtensionWorker')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50, null=True)),
                ('unit_of_measure', models.CharField(max_length=10, null=True)),
                ('company_image', models.ImageField(null=True, upload_to='processors')),
                ('primary_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.Crop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('estimated_yield', models.IntegerField()),
                ('season_active', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Farm')),
            ],
        ),
        migrations.AddField(
            model_name='farmreport',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.Season'),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.Season'),
        ),
        migrations.AddField(
            model_name='farm',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Processor'),
        ),
        migrations.AddField(
            model_name='extensionworker',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Processor'),
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.FarmReport'),
        ),
        migrations.AddField(
            model_name='cropinputs',
            name='farm_crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.FarmCrop'),
        ),
    ]
