# Generated by Django 2.1.7 on 2019-03-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.Crop'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
