# Generated by Django 2.1.7 on 2019-03-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropinputs',
            name='farm_crop',
        ),
        migrations.RemoveField(
            model_name='cropmanagement',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='cropmanagement',
            name='report',
        ),
        migrations.RemoveField(
            model_name='farmanimals',
            name='farm_id',
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='season',
        ),
        migrations.RemoveField(
            model_name='farmreport',
            name='farm_id',
        ),
        migrations.RemoveField(
            model_name='farmreport',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='farmreport',
            name='season',
        ),
        migrations.DeleteModel(
            name='CropInputs',
        ),
        migrations.DeleteModel(
            name='CropManagement',
        ),
        migrations.DeleteModel(
            name='FarmAnimals',
        ),
        migrations.DeleteModel(
            name='FarmCrop',
        ),
        migrations.DeleteModel(
            name='FarmReport',
        ),
    ]
