# Generated by Django 2.1.7 on 2019-03-09 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='average_investment_per_season',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='average_price_per_season',
        ),
        migrations.AddField(
            model_name='requests',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='investment',
            field=models.IntegerField(default=0),
        ),
    ]
