# Generated by Django 2.1.7 on 2019-03-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20190304_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmAnimals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=50)),
                ('number_of_animals', models.IntegerField()),
                ('percentage_as_manure', models.IntegerField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Farm')),
            ],
        ),
    ]
