# Generated by Django 2.1.7 on 2019-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20190309_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmreport',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
