# Generated by Django 2.1.7 on 2019-03-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_farmanimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_crop', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Crop')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.Season')),
            ],
        ),
        migrations.CreateModel(
            name='FarmReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Farm')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.ExtensionWorker')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.Season')),
            ],
        ),
    ]
