# Generated by Django 2.1.7 on 2019-03-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20190309_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='season',
        ),
        migrations.AddField(
            model_name='requests',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.FarmReport'),
        ),
    ]
