# Generated by Django 2.1.7 on 2019-03-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_farmcrop_farmreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('product_quantity', models.IntegerField()),
                ('product_quantity_si', models.CharField(max_length=10)),
                ('date_of_use', models.DateField()),
                ('farm_crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.FarmCrop')),
            ],
        ),
        migrations.CreateModel(
            name='CropManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=400)),
                ('activity_status', models.CharField(max_length=300)),
                ('comment', models.TextField()),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.Crop')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.FarmReport')),
            ],
        ),
    ]
