# Generated by Django 2.1.7 on 2019-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_cropinputs_cropmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmpractices',
            name='animal_manure_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmpractices',
            name='compost_used_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
