# Generated by Django 2.1.7 on 2019-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_auto_20190304_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_organic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
