# Generated by Django 2.1.7 on 2019-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_farm_is_organic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='date_added',
            field=models.DateField(),
        ),
    ]
