# Generated by Django 2.1.7 on 2019-03-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0008_auto_20190305_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropinputs',
            name='farm_crop',
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='season',
        ),
        migrations.AddField(
            model_name='cropinputs',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.FarmReport'),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.FarmReport'),
        ),
    ]
