# Generated by Django 2.1.7 on 2019-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0009_auto_20190306_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
