# Generated by Django 2.1.7 on 2019-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0010_farmcrop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionworker',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='workers'),
        ),
        migrations.AlterField(
            model_name='extensionworker',
            name='started_work',
            field=models.DateField(auto_now=True),
        ),
    ]
