# Generated by Django 2.1.7 on 2019-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0011_auto_20190307_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionworker',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
